### PR TITLE
Optimise record serialisation

### PR DESCRIPTION
**Pull request by jwkohnen**
I've benchmarked a few string concatenations. It turns out, that out of `fmt.Sprintf`, `strings.Builder`, `strings.Builder` with pre-grow and naive `+`-concat, the latter is the fastest. 

I had the assumption that string concat is special cased in the runtime for up to five operands, but possibly that is not true (anymore). 

```
name \ time/op    printf      buffer      pregrow     concat
Serialization-8   490ns ¬± 1%  245ns ¬± 2%  169ns ¬± 1%  109ns ¬± 1%

name \ alloc/op   printf      buffer      pregrow     concat
Serialization-8    160B ¬± 0%   128B ¬± 0%    96B ¬± 0%     0B     

name \ allocs/op  printf      buffer      pregrow     concat
Serialization-8    8.00 ¬± 0%   6.00 ¬± 0%   4.00 ¬± 0%   0.00     
```

### CODE REVIEW

**Comment by jwkohnen** [comment]
benchstat of `+`-concat with different Go version (all darwin/amd64):

```
name \ time/op    go1.11.13   go1.12.17   go1.13.8
Serialization-8   112ns ± 2%  111ns ± 4%  109ns ± 1%

name \ alloc/op   go1.11.13   go1.12.17   go1.13.8
Serialization-8   0.00B       0.00B       0.00B

name \ allocs/op  go1.11.13   go1.12.17   go1.13.8
Serialization-8    0.00        0.00        0.00
```

**Comment by dgryski** [comment]
The line protocol and tcp write probably want []byte instead of string.  Might be worth updating the return value here.  Also, `*string` is almost never what you want.  A `string` is a two-word struct (data pointer, string length).  It ought to be passed by value.

**Comment by grzkv** [comment]
@dgryski Yes. Thanks for pointing this out. We should probably migrate the whole codebase to using `[]byte` instead of `string`.

**Comment by azhiltsov** [comment]
> @dgryski Yes. Thanks for pointing this out. We should probably migrate the whole codebase to using `[]byte` instead of `string`.

Wouldn't this require a string validation then, which is currently comes with the 'string' type?

**Comment by grzkv** [comment]
@azhiltsov We may have to keep the `string` type in some places for conversions. But the thing is, we already treat `string` as `[]byte` in many places. I will look into this.

**Pull request merged**
