### PR TITLE
Patched packages paths to point to github

### PR DESCRIPTION
**Pull request by grzkv**

### CODE REVIEW

**Comment by grlvrl** [comment]
The changes look good to me. What about package-update in "nanotube/test/receiver/receiver.go" ?

**Comment by avereha** [comment]
If we sync our internal gitlab repo from this one, is the build going to work after this change?

**Comment by grzkv** [comment]
@avereha We will figure out the internal part.
In any case, this change is required for the packages to behave correctly.

**Comment by avereha** [comment]
I don't understand what problem we are trying to solve.
Can we please update the commit message?

**Pull request merged**
